# Generated by Django 4.1.2 on 2022-10-16 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helphand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeradvert',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='helphand.fundraiser'),
        ),
    ]
