# Generated by Django 4.1.2 on 2022-10-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helphand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='created_by',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='volunteeradvert',
            name='created_by',
            field=models.IntegerField(default=-1),
        ),
    ]
