# Generated by Django 4.1.2 on 2022-10-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helphand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeradvert',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='volunteeradvert',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='volunteeradvert',
            name='image',
            field=models.ImageField(upload_to='volunteer_photos'),
        ),
        migrations.AlterField(
            model_name='volunteeradvert',
            name='role',
            field=models.CharField(max_length=80),
        ),
    ]
