# Generated by Django 4.1.2 on 2022-10-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helphand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
