# Generated by Django 4.1.2 on 2022-10-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helphand', '0002_alter_volunteeradvert_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='image',
            field=models.ImageField(blank=True, upload_to='fundraiser_photos'),
        ),
        migrations.AlterField(
            model_name='volunteeradvert',
            name='image',
            field=models.ImageField(blank=True, upload_to='volunteer_photos'),
        ),
    ]
