# Generated by Django 4.1.2 on 2022-10-12 16:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('helphand', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PL', unique=True)),
                ('fundraiser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='VolunteerAdvert', to='helphand.fundraiser')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('volunteer_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VolunteerPhoto', to='helphand.volunteeradvert')),
            ],
        ),
        migrations.DeleteModel(
            name='Fundraisers',
        ),
    ]
