# Generated by Django 4.1.2 on 2022-10-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helphand', '0004_alter_volunteeradvert_fundraiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeradvert',
            name='image',
            field=models.ImageField(blank=True, upload_to='volunteer_photos'),
        ),
    ]
